import Head from "next/head";
import IntroductionBillBoard from "./components/IntroductionBillBoard";
import StoreNav from "./components/StoreNav";
import PaginationSlider from "./components/PaginationSlider";
import ItemCategory from "./components/ItemCategory";
import SaleSection from "./components/SaleSection";
import Footer from "./components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Fashion store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <StoreNav />

        <div className="relative pt-[100px] ">
          <img className="bg-cover" src="/banner-bg3.jpg" />
          <div className="absolute left-[200px] top-1/2 -translate-y-1/2  transform">
            <IntroductionBillBoard />
          </div>
        </div>
        <ItemCategory />

        <div className="flex items-center justify-center">
          <div className="flex-grow border-t border-gray-300"></div>
          <div className="mx-4 text-4xl font-bold">Best Selling Products</div>
          <div className="flex-grow border-t border-gray-300"></div>
        </div>
        <div className="mt-20 ">
          <PaginationSlider />
        </div>
        <div className="mb-20">
          <SaleSection />
        </div>
        <Footer />
      </div>
    </>
  );
}
